import streamlit as st
import pandas as pd # Added for CSV handling
from datetime import date
from bot import SYSTEM_INSTRUCTION, MODEL, generate_response, create_model 
import re
import time

# For canvas conversion
from streamlit_drawable_canvas import st_canvas
import numpy as np
from PIL import Image
from io import BytesIO

# Define session state variables so streamlit remembers chat history
if "search_clicked" not in st.session_state:
    st.session_state.search_clicked = False

if "response" not in st.session_state:
    st.session_state.response = None

if "target_link" not in st.session_state:
    st.session_state.target_link = None

if "messages" not in st.session_state:
    st.session_state.messages = []

# Icon from their website window icon
ICON_LINK: str = "https://encrypted-tbn2.gstatic.com/faviconV2?url=https://reelvendornetwork.com&client=VFE&size=64&type=FAVICON&fallback_opts=TYPE,SIZE,URL&nfrp=2"
LOGO_LINK: str = "https://reelvendornetwork.com/wp-content/uploads/2024/09/Gradient-Logo2.png"

# If True, the Gemini bot isn't activated to not waste any credits.
DEMO_MODE: bool = True 

# If chat mode not yet created with memory, create it
if "chat_session" not in st.session_state:
    st.session_state.chat_session = create_model()

MODEL_SESSION = st.session_state.chat_session

def local_css(file_name):
    with open(file_name) as f:
        st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)

st.set_page_config(page_title="Reel Vendor Network", page_icon=ICON_LINK, layout="wide")

# Set style
with open("style.css") as f:
    st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)
    
st.title("Reel Vendor Assistant")
# st.image("https://reelvendornetwork.com/wp-content/uploads/2024/09/Gradient-Logo2.png",width=100)

# --- DATA LOADING ---
@st.cache_data
def load_vendor_data():
    # Load the CSV of vendor links as a dataframe. If it doesn't exist, provide a fallback
    try:
        df = pd.read_csv("links.csv")
        return df
    except FileNotFoundError:
        return pd.DataFrame({"Category": ["Venue"], "URL": ["https://reelvendornetwork.com/venues/"]})

vendor_df = load_vendor_data()

def build_parts(response) -> list:   

    # For demo purposes to not waste API credits
    if DEMO_MODE: # or if response is str as generate response in demo mode returns str      
        return [response]
    
    elif not hasattr(response, 'candidates') or not response.candidates or None:
        return ['No response generated by the model.']
    
    # Combine all parts into one string
    full_text = "".join([part.text for part in response.candidates[0].content.parts if part.text])

    # Avoids latex formatting issues by ignoring '$' cmd
    full_text.replace('$', '\$')  

    # Split by header while keeping the header
    raw_sections = re.split(r'(?m)^(?=#)', full_text)
    return [s.strip() for s in raw_sections if s.strip()]

    # Grounding metadata (hidden for now)
    # metadata = response.candidates[0].grounding_metadata
    # if metadata and metadata.search_entry_point:
    #     st.markdown("---")
        # st.caption("Sources & Grounding:")
        # st.markdown(metadata.search_entry_point.rendered_content, unsafe_allow_html=True)

def convert_canvas(canvas) -> Image:
    """
    TODO CONVERT TO PNG OR SOMETHING FOR THE MODEL TO READ
    Takes CanvasResult object
    """
    raw_data = canvas.image_data

    # 2. Reshape/Squeeze if it's 4D
    if raw_data.ndim == 4:
        # Taking the first image in the batch
        img_array = raw_data[0].astype(np.uint8)
    else:
        img_array = raw_data.astype(np.uint8)

    # 3. Create the Image object (mode 'RGBA')
    img = Image.fromarray(img_array, 'RGBA')

    return img 

def format_conversation():
    content = "# Reel Vendor Assistant - Chat History\n\n"
    
    # Add the initial search result if it exists
    if st.session_state.response:
        content += "## Initial Search Results\n"
        # Since response might be a complex object, we extract the text
        if hasattr(st.session_state.response, 'candidates'):
             full_text = "".join([part.text for part in st.session_state.response.candidates[0].content.parts if part.text])
             content += full_text + "\n\n"
    
    content += "## Follow-up Discussion\n"
    for msg in st.session_state.messages:
        role = "Assistant" if msg["role"] == "ai" else "User"
        # Your AI messages are stored as lists (from build_parts), so join them
        msg_text = "\n".join(msg["content"]) if isinstance(msg["content"], list) else msg["content"]
        content += f"**{role}:** {msg_text}\n\n"
        
    return content

# --- SIDEBAR FORM ---
with st.sidebar:
    st.logo(LOGO_LINK)

    with st.form("wedding_criteria"):

        st.subheader("Vendor Selection")
    
        selected_category = st.selectbox(
            label="Select",
            options=vendor_df["Category"].tolist(),
            index=None, # Is a required selection
            placeholder="Select a Vendor",
            label_visibility="collapsed"
        )

        st.subheader("Basics")

        wedding_date = st.date_input("Wedding Date", min_value=date.today())
        location = st.text_input("Location or Venue", placeholder="e.g. Newport, RI",value="New England")
        guest_range = st.selectbox("Estimated Guest Count", ["N/A","0-50", "50-100", "100-150", "150+"])
        setting = st.selectbox("Setting", ["N/A","Indoor", "Outdoor", "Both"])

        st.subheader("Style & Vision")

        style = st.text_input("Style/Theme", placeholder="e.g. Coastal, Vintage, Cultural")
        vibe_tags = st.multiselect(
            "Overall Vibe",
            ["Modern", "Romantic", "Cinematic", "Fun", "Luxury", "Classic", "Edgy"]
        )
        
        # st.subheader("Inspiration Photos")

        uploaded_pictures = []

        uploaded_pictures = st.file_uploader(
            "Inspiration Photos",
            type=["png", "jpg", "jpeg", "webp"],
            accept_multiple_files=True,
            help="Upload wedding inspiration photos to help guide the vendor search."
        )

        st.write("Or sketch an idea:")
        canvas_result = st_canvas(
            stroke_width=3,
            stroke_color="#000000",
            background_color="#EEEEEE",
            height=250, # Scaled down for the sidebar
            width=250,  # Scaled down for the sidebar
            drawing_mode="freedraw",
            key="canvas"
        )
        
        # Give model canvas picture if filled in
        if canvas_result.json_data is not None and len(canvas_result.json_data.get("objects", [])) > 0:
            picture = convert_canvas(canvas_result)
            uploaded_pictures.append(picture)

        if uploaded_pictures:
            st.write("Preview:")
            for img in uploaded_pictures:
                st.image(img, caption=None, use_container_width=True)

        st.subheader("Budget & Priorities")

        budget = st.text_input("Budget range for this vendor")
        notes = st.text_area("Special Requests / Deal Breakers")

        submit_button = st.form_submit_button("Find My Vendor")

        if st.session_state.search_clicked:
            chat_log = format_conversation()
            
            st.sidebar.download_button(
                label="💾 Save Conversation",
                data=chat_log,
                file_name=f"wedding_vendors_{selected_category}_{date.today()}.md",
                mime="text/markdown",
            )

# QUERY  
if submit_button:
    if not selected_category: # TODO AND CHECK BOX IS NOT CHECKED.
        st.error("Please select a vendor category, or select \"make me a wedding\" before searching.")
        st.stop() # This halts the script so the code below doesn't run

    st.session_state.search_clicked = True
    st.session_state.messages = []   # reset chat for new vendor search

    # Reset the model session for a fresh start with the new vendor category
    # st.session_state.chat_session = create_model()

    # LINK LOOKUP: Find the URL associated with the selection
    target_link = vendor_df[vendor_df["Category"] == selected_category]["URL"].values[0]
    st.session_state.target_link = target_link # Save link to state

    # INJECTING THE VALUES TO QUERY: Updated query with specific requirements
    profile_text = f"""
    You are searching specifically for a {selected_category}.
    
    Quietly follow these steps without writing the output:
    STEP 1: Use the link {target_link} to find the best {selected_category} vendors.
    STEP 2: Once you find names, search Google for more details on those specific vendors.

    Use the following wedding profile, if applicable, for more context:

    USER WEDDING PROFILE:
    - Date: {wedding_date}
    - Location: {location}
    - Guest Size: {guest_range}
    - Style/Vibe: {style} ({', '.join(vibe_tags)})
    - Budget: {budget}
    - Notes: {notes}

    INSTRUCTIONS:
    1. Provide 3 reccomended vendors from {selected_category}s found at {target_link}. 
        1a. If there are less than 3 available vendors, only list those. Do not search the web for more.
    2. Filter results from the Reel link to only include vendors relevant to the specified location. 
        2a. If no matches exist, state: "I could not find any Reel vendors serving {location}." 
        and list the available locations for the vendors on that page.
    3. For each, include: **Vendor Name**, **Summary**, and a **'Why they fit'** section.
    4. Keep it concise. Use Markdown headers for each vendor.
    5. Only provide links to the actual vendor's website, not on Reel vendor network's website.
    6. Use markdown text only. You may use math to rationalize a budget but do not use Latex or code snippets.
    7. If the user adds any image or sketch input, make sure to acknowledge, and comment positivley.
    """
    print("\n",profile_text)

    try:    # VENDOR RESULT
        # can try st.status to recieve updates from gemin
        # and then st.write(f"Analyzing {selected_category} based on your needs")
        with st.spinner(f"Searching {selected_category} options at Reel Vendor Network..."):
            st.session_state.response = generate_response(
                profile_text, 
                MODEL_SESSION, 
                images=uploaded_pictures, 
                demo=DEMO_MODE
            )
    except Exception as e:
        st.error(f"An error occurred: {e}")

if st.session_state.search_clicked:
    st.markdown(f"See more {selected_category}s at {st.session_state.target_link}")

    text_sections = build_parts(st.session_state.response)
    
    for section in text_sections:
        with st.chat_message("ai", avatar=ICON_LINK):
            st.markdown(section)

    # show previous follow-up chat messages
    for message in st.session_state.messages:
        with st.chat_message(message["role"], avatar=ICON_LINK if message["role"] == "ai" else None):
            st.markdown(message["content"])
    
    # CHAT INPUT
    prompt = st.chat_input("Say something")

    # When user inputs a prompt
    if prompt:
        # Save and show user message
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.write(prompt)

        # Generate bot response
        response = generate_response(prompt, MODEL_SESSION, demo=DEMO_MODE)

        text_sections = build_parts(response)
        full_response_text = "\n\n".join(text_sections)

        # Save and show bot response
        st.session_state.messages.append({"role": "ai", "content": full_response_text})

        with st.chat_message("ai", avatar=ICON_LINK):
            for section in text_sections:
                st.markdown(section)
        st.rerun()
