"""
utils.py — Image processing & response parsing helpers.
All functions are pure utilities with no direct Streamlit UI side-effects.
"""

import re
import numpy as np
from PIL import Image
from io import BytesIO


# ── RESPONSE PARSING ──────────────────────────────────────────────────────────

def build_parts(response, demo: bool = False) -> list[str]:
    """
    Parse a Gemini response object into a list of markdown section strings.
    In demo mode, wraps the raw response string in a list.
    """
    if demo:
        return [response]

    if not hasattr(response, "candidates") or not response.candidates:
        return ["No response generated by the model."]

    parts = response.candidates[0].content.parts if response.candidates[0].content else None
    if not parts:
        return ["No response generated by the model."]

    # Combine all parts into one string
    full_text = "".join(
        part.text for part in parts if part.text
    )

    # Avoids latex formatting issues by ignoring '$' cmd
    full_text = full_text.replace("$", "\\$")

    # Split by header while keeping the header
    raw_sections = re.split(r"(?m)^(?=#)", full_text)
    return [s.strip() for s in raw_sections if s.strip()]


# ── IMAGE PROCESSING ──────────────────────────────────────────────────────────

def convert_canvas(canvas) -> bytes | None:
    """
    Convert Streamlit drawable canvas output into PNG bytes for model input.
    Returns None if the canvas is empty.
    """
    if canvas.image_data is None:
        return None

    raw_data = canvas.image_data

    if raw_data.ndim == 4:
        img_array = raw_data[0].astype(np.uint8)
    else:
        img_array = raw_data.astype(np.uint8)

    img = Image.fromarray(img_array, "RGBA")

    buf = BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


def uploaded_file_png(uploaded_file) -> bytes:
    """Convert an uploaded image file to PNG bytes for consistent model input."""
    img = Image.open(uploaded_file).convert("RGBA")
    buf = BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


# ── CONVERSATION EXPORT ───────────────────────────────────────────────────────

def format_conversation(response, messages: list[dict]) -> str:
    """
    Build a downloadable Markdown string from the initial search response
    and subsequent follow-up messages.
    """
    content = "# Reel Vendor Assistant - Chat History\n\n"

    # Add the initial search result if it exists
    if response:
        content += "## Initial Search Results\n"
        if hasattr(response, "candidates"):
            full_text = "".join(
                part.text
                for part in response.candidates[0].content.parts
                if part.text
            )
            content += full_text + "\n\n"

    content += "## Follow-up Discussion\n"
    for msg in messages:
        role = "Assistant" if msg["role"] == "ai" else "User"
        # AI messages may be stored as lists (from build_parts), so join them
        msg_text = (
            "\n".join(msg["content"])
            if isinstance(msg["content"], list)
            else msg["content"]
        )
        content += f"**{role}:** {msg_text}\n\n"

    return content
